import {
  LayoutDashboard,
  Trophy,
  FileText,
  Headphones,
  Award,
  Code2,
  Keyboard,
  BookOpen,
  GraduationCap,
  Terminal,
  Cpu,
  GitFork,
  Users,
  Newspaper,
  ShieldAlert,
  UserCircle2,
} from "lucide-react";

export const NAV_ITEMS = [
  { label: "Dashboard", href: "/user/dashboard", icon: LayoutDashboard },
  { label: "Leaderboard", href: "/user/leaderboard", icon: Trophy },
  { label: "Assessments", href: "/user/assessments", icon: FileText },
  { label: "LSRW", href: "/user/lsrw", icon: Headphones },
  { label: "Practice", href: "/user/practice", icon: Award },
  { label: "CodeArena", href: "/user/codearena", icon: Code2 },
  { label: "Typing Test", href: "/user/typing-test", icon: Keyboard },
  { label: "Courses", href: "/user/courses", icon: BookOpen },
  { label: "Trainings", href: "/user/trainings", icon: GraduationCap },
  { label: "Codespace", href: "/user/codespace", icon: Terminal },
  { label: "CodeX", href: "/user/codex", icon: Cpu },
  { label: "DSA Visualizer", href: "/user/dsa-visualizer", icon: GitFork },
  { label: "Pair Programming", href: "/user/pair-programming", icon: Users },
  { label: "Blogs", href: "/user/blogs", icon: Newspaper },
  { label: "PenTest Lab", href: "/user/pentest-lab", icon: ShieldAlert },
  { label: "Profile", href: "/user/profile", icon: UserCircle2 },
] as const;
